### ISSUE TITLE
Tests doesn't end automatically 

### ISSUE THREAD

**Issue by arindam89** [alex-pollan/gulp-jasmine-node#2]
Tests doesn't end automatically and we need to hit ctrl+c to exit.

This is stopping us from getting the coverage report.

**Comment by alex-pollan** [comment]
Please check that the _done_ callback is present and called in asynchronous code tests.
Would you please send me the gulp file code block and the test code block that is not terminating?

**Comment by jeffhall4** [comment]
I see the same issue when using gulp 4 and the tests complete successfully. The issue appears to be in the flush function of the pipe. The callback is only called if there is an error and not on success. I've submitted a PR that addresses the issue.
